apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: hello-openshift
  namespace: example
spec:
  containers:
    - name: hello-openshift
      image: openshift/hello-openshift
      ports:
        - containerPort: 8080
      env:
        - name: ENV-VAR-1
          value: ${ENV-VAR-1}
        - name: ENV-VAR-2
          value: ${ENV-VAR-1}
