apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: "Example Jenkins Pipeline Template"
  name: example-jenkins-pipeline-template
parameters:
  - name: ENV_VAR_1
    description: First env var
    required: true
  - name: ENV_VAR_2
    description: Second env var
    required: true
  - name: ENVIRONMENT
    description: ENVIRONMENT of the application (e.g. dev,test,prod)
    required: true
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: example
    labels:
      app: hello-openshift
    namespace: example-${ENVIRONMENT}
  spec:
    containers:
      - name: hello-openshift
        image: openshift/hello-openshift
        ports:
          - containerPort: 8080
        env:
          - name: ENV_VAR_1
            value: ${ENV_VAR_1}
          - name: ENV_VAR_2
            value: ${ENV_VAR_2}
